# Initially generated by ChatGPT
# launch it to set up a new database
import sqlite3

# Create a connection to the database (or create it if it doesn't exist)
conn = sqlite3.connect('dictionary.db')

# Create a cursor to execute SQL commands
c = conn.cursor()

# Create the table for lexemes and grammatical classes
c.execute('''CREATE TABLE lexemes (
                id INTEGER PRIMARY KEY,
                lexeme TEXT NOT NULL,
                grammatical_class TEXT NOT NULL
            )''')

# Create the table for translations
c.execute('''CREATE TABLE translations (
                id INTEGER PRIMARY KEY,
                lexeme_id INTEGER NOT NULL,
                translation TEXT NOT NULL,
                langcode TEXT NOT NULL,
                FOREIGN KEY (lexeme_id) REFERENCES lexemes(id)
            )''') ## added "langcode" field

# Create the table for variants of lexemes
c.execute('''CREATE TABLE variants (
                id INTEGER PRIMARY KEY,
                lexeme_id INTEGER NOT NULL,
                variant TEXT NOT NULL,
                FOREIGN KEY (lexeme_id) REFERENCES lexemes(id)
            )''')

# Commit the changes and close the connection
conn.commit()
conn.close()
